// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v6.31.1
// source: api/proto/v1/flag_service.proto

package flagspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchFlagEventType int32

const (
	WatchFlagEventType_WATCH_FLAG_EVENT_TYPE_UNSPECIFIED WatchFlagEventType = 0
	WatchFlagEventType_FLAG_UPDATED                      WatchFlagEventType = 1
	WatchFlagEventType_FLAG_DELETED                      WatchFlagEventType = 2
)

// Enum value maps for WatchFlagEventType.
var (
	WatchFlagEventType_name = map[int32]string{
		0: "WATCH_FLAG_EVENT_TYPE_UNSPECIFIED",
		1: "FLAG_UPDATED",
		2: "FLAG_DELETED",
	}
	WatchFlagEventType_value = map[string]int32{
		"WATCH_FLAG_EVENT_TYPE_UNSPECIFIED": 0,
		"FLAG_UPDATED":                      1,
		"FLAG_DELETED":                      2,
	}
)

func (x WatchFlagEventType) Enum() *WatchFlagEventType {
	p := new(WatchFlagEventType)
	*p = x
	return p
}

func (x WatchFlagEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchFlagEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_flag_service_proto_enumTypes[0].Descriptor()
}

func (WatchFlagEventType) Type() protoreflect.EnumType {
	return &file_api_proto_v1_flag_service_proto_enumTypes[0]
}

func (x WatchFlagEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchFlagEventType.Descriptor instead.
func (WatchFlagEventType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_flag_service_proto_rawDescGZIP(), []int{0}
}

type Flag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key          string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Description  string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Enabled      bool   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	VariantsJson []byte `protobuf:"bytes,4,opt,name=variants_json,json=variantsJson,proto3" json:"variants_json,omitempty"`
	RulesJson    []byte `protobuf:"bytes,5,opt,name=rules_json,json=rulesJson,proto3" json:"rules_json,omitempty"`
}

func (x *Flag) Reset() {
	*x = Flag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_flag_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Flag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag) ProtoMessage() {}

func (x *Flag) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_flag_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag.ProtoReflect.Descriptor instead.
func (*Flag) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_flag_service_proto_rawDescGZIP(), []int{0}
}

func (x *Flag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Flag) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Flag) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Flag) GetVariantsJson() []byte {
	if x != nil {
		return x.VariantsJson
	}
	return nil
}

func (x *Flag) GetRulesJson() []byte {
	if x != nil {
		return x.RulesJson
	}
	return nil
}

type CreateFlagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag *Flag `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *CreateFlagRequest) Reset() {
	*x = CreateFlagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_flag_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlagRequest) ProtoMessage() {}

func (x *CreateFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_flag_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlagRequest.ProtoReflect.Descriptor instead.
func (*CreateFlagRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_flag_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFlagRequest) GetFlag() *Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

type CreateFlagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag *Flag `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *CreateFlagResponse) Reset() {
	*x = CreateFlagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_flag_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlagResponse) ProtoMessage() {}

func (x *CreateFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_flag_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlagResponse.ProtoReflect.Descriptor instead.
func (*CreateFlagResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_flag_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFlagResponse) GetFlag() *Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

type UpdateFlagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag *Flag `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *UpdateFlagRequest) Reset() {
	*x = UpdateFlagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_flag_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFlagRequest) ProtoMessage() {}

func (x *UpdateFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_flag_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFlagRequest.ProtoReflect.Descriptor instead.
func (*UpdateFlagRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_flag_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateFlagRequest) GetFlag() *Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

type UpdateFlagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag *Flag `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *UpdateFlagResponse) Reset() {
	*x = UpdateFlagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_flag_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFlagResponse) ProtoMessage() {}

func (x *UpdateFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_flag_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFlagResponse.ProtoReflect.Descriptor instead.
func (*UpdateFlagResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_flag_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateFlagResponse) GetFlag() *Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

type GetFlagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetFlagRequest) Reset() {
	*x = GetFlagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_flag_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlagRequest) ProtoMessage() {}

func (x *GetFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_flag_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlagRequest.ProtoReflect.Descriptor instead.
func (*GetFlagRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_flag_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetFlagRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetFlagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag *Flag `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *GetFlagResponse) Reset() {
	*x = GetFlagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_flag_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlagResponse) ProtoMessage() {}

func (x *GetFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_flag_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlagResponse.ProtoReflect.Descriptor instead.
func (*GetFlagResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_flag_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetFlagResponse) GetFlag() *Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

type ListFlagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageSize  int32  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
}

func (x *ListFlagsRequest) Reset() {
	*x = ListFlagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_flag_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFlagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlagsRequest) ProtoMessage() {}

func (x *ListFlagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_flag_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlagsRequest.ProtoReflect.Descriptor instead.
func (*ListFlagsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_flag_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListFlagsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFlagsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListFlagsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flags         []*Flag `protobuf:"bytes,1,rep,name=flags,proto3" json:"flags,omitempty"`
	NextPageToken string  `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
}

func (x *ListFlagsResponse) Reset() {
	*x = ListFlagsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_flag_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFlagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlagsResponse) ProtoMessage() {}

func (x *ListFlagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_flag_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlagsResponse.ProtoReflect.Descriptor instead.
func (*ListFlagsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_flag_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListFlagsResponse) GetFlags() []*Flag {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *ListFlagsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type DeleteFlagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *DeleteFlagRequest) Reset() {
	*x = DeleteFlagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_flag_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFlagRequest) ProtoMessage() {}

func (x *DeleteFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_flag_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFlagRequest.ProtoReflect.Descriptor instead.
func (*DeleteFlagRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_flag_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteFlagRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteFlagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteFlagResponse) Reset() {
	*x = DeleteFlagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_flag_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFlagResponse) ProtoMessage() {}

func (x *DeleteFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_flag_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFlagResponse.ProtoReflect.Descriptor instead.
func (*DeleteFlagResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_flag_service_proto_rawDescGZIP(), []int{10}
}

type ResolveBooleanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key          string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ContextJson  []byte `protobuf:"bytes,2,opt,name=context_json,json=contextJson,proto3" json:"context_json,omitempty"`
	DefaultValue bool   `protobuf:"varint,3,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
}

func (x *ResolveBooleanRequest) Reset() {
	*x = ResolveBooleanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_flag_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveBooleanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveBooleanRequest) ProtoMessage() {}

func (x *ResolveBooleanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_flag_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveBooleanRequest.ProtoReflect.Descriptor instead.
func (*ResolveBooleanRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_flag_service_proto_rawDescGZIP(), []int{11}
}

func (x *ResolveBooleanRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ResolveBooleanRequest) GetContextJson() []byte {
	if x != nil {
		return x.ContextJson
	}
	return nil
}

func (x *ResolveBooleanRequest) GetDefaultValue() bool {
	if x != nil {
		return x.DefaultValue
	}
	return false
}

type ResolveBooleanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value bool   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ResolveBooleanResponse) Reset() {
	*x = ResolveBooleanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_flag_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveBooleanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveBooleanResponse) ProtoMessage() {}

func (x *ResolveBooleanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_flag_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveBooleanResponse.ProtoReflect.Descriptor instead.
func (*ResolveBooleanResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_flag_service_proto_rawDescGZIP(), []int{12}
}

func (x *ResolveBooleanResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ResolveBooleanResponse) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type ResolveBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests []*ResolveBooleanRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *ResolveBatchRequest) Reset() {
	*x = ResolveBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_flag_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveBatchRequest) ProtoMessage() {}

func (x *ResolveBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_flag_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveBatchRequest.ProtoReflect.Descriptor instead.
func (*ResolveBatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_flag_service_proto_rawDescGZIP(), []int{13}
}

func (x *ResolveBatchRequest) GetRequests() []*ResolveBooleanRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type ResolveBatchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value bool   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ResolveBatchResult) Reset() {
	*x = ResolveBatchResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_flag_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveBatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveBatchResult) ProtoMessage() {}

func (x *ResolveBatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_flag_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveBatchResult.ProtoReflect.Descriptor instead.
func (*ResolveBatchResult) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_flag_service_proto_rawDescGZIP(), []int{14}
}

func (x *ResolveBatchResult) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ResolveBatchResult) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type ResolveBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*ResolveBatchResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *ResolveBatchResponse) Reset() {
	*x = ResolveBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_flag_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveBatchResponse) ProtoMessage() {}

func (x *ResolveBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_flag_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveBatchResponse.ProtoReflect.Descriptor instead.
func (*ResolveBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_flag_service_proto_rawDescGZIP(), []int{15}
}

func (x *ResolveBatchResponse) GetResults() []*ResolveBatchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type WatchFlagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key         string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	LastEventId int64  `protobuf:"varint,2,opt,name=last_event_id,json=lastEventId,proto3" json:"last_event_id,omitempty"`
}

func (x *WatchFlagRequest) Reset() {
	*x = WatchFlagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_flag_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchFlagRequest) ProtoMessage() {}

func (x *WatchFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_flag_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchFlagRequest.ProtoReflect.Descriptor instead.
func (*WatchFlagRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_flag_service_proto_rawDescGZIP(), []int{16}
}

func (x *WatchFlagRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WatchFlagRequest) GetLastEventId() int64 {
	if x != nil {
		return x.LastEventId
	}
	return 0
}

type WatchFlagEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    WatchFlagEventType `protobuf:"varint,1,opt,name=type,proto3,enum=flagz.v1.WatchFlagEventType" json:"type,omitempty"`
	Key     string             `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Flag    *Flag              `protobuf:"bytes,3,opt,name=flag,proto3" json:"flag,omitempty"`
	EventId int64              `protobuf:"varint,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
}

func (x *WatchFlagEvent) Reset() {
	*x = WatchFlagEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_flag_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchFlagEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchFlagEvent) ProtoMessage() {}

func (x *WatchFlagEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_flag_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchFlagEvent.ProtoReflect.Descriptor instead.
func (*WatchFlagEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_flag_service_proto_rawDescGZIP(), []int{17}
}

func (x *WatchFlagEvent) GetType() WatchFlagEventType {
	if x != nil {
		return x.Type
	}
	return WatchFlagEventType_WATCH_FLAG_EVENT_TYPE_UNSPECIFIED
}

func (x *WatchFlagEvent) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WatchFlagEvent) GetFlag() *Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

func (x *WatchFlagEvent) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

var File_api_proto_v1_flag_service_proto protoreflect.FileDescriptor

var file_api_proto_v1_flag_service_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x66,
	0x6c, 0x61, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x66, 0x6c, 0x61, 0x67, 0x7a, 0x2e, 0x76, 0x31, 0x22, 0x98, 0x01, 0x0a, 0x04,
	0x46, 0x6c, 0x61, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x5f, 0x6a,
	0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x76, 0x61, 0x72, 0x69, 0x61,
	0x6e, 0x74, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x75, 0x6c, 0x65, 0x73,
	0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x72, 0x75, 0x6c,
	0x65, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x37, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x66,
	0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x6c, 0x61, 0x67,
	0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22,
	0x38, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x46,
	0x6c, 0x61, 0x67, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x37, 0x0a, 0x11, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22,
	0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66,
	0x6c, 0x61, 0x67, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x04, 0x66, 0x6c,
	0x61, 0x67, 0x22, 0x38, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x7a, 0x2e, 0x76,
	0x31, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x22, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x35, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6c, 0x61,
	0x67, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x4e, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x46,
	0x6c, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61,
	0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x61, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x46,
	0x6c, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x05,
	0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x6c,
	0x61, 0x67, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x05, 0x66, 0x6c, 0x61,
	0x67, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x65, 0x78,
	0x74, 0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x25, 0x0a, 0x11, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x71, 0x0a, 0x15, 0x52, 0x65, 0x73, 0x6f, 0x6c,
	0x76, 0x65, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x6a, 0x73,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x40, 0x0a, 0x16, 0x52, 0x65,
	0x73, 0x6f, 0x6c, 0x76, 0x65, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x52, 0x0a, 0x13,
	0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x7a, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73,
	0x22, 0x3c, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4e,
	0x0a, 0x14, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x7a, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x48,
	0x0a, 0x10, 0x57, 0x61, 0x74, 0x63, 0x68, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x61, 0x73,
	0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x93, 0x01, 0x0a, 0x0e, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x46, 0x6c, 0x61, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x66, 0x6c, 0x61, 0x67,
	0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x46, 0x6c, 0x61, 0x67, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x22, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x66, 0x6c, 0x61, 0x67, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x04, 0x66,
	0x6c, 0x61, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x2a, 0x5f,
	0x0a, 0x12, 0x57, 0x61, 0x74, 0x63, 0x68, 0x46, 0x6c, 0x61, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x21, 0x57, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x46, 0x4c,
	0x41, 0x47, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x46,
	0x4c, 0x41, 0x47, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x10, 0x0a,
	0x0c, 0x46, 0x4c, 0x41, 0x47, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x02, 0x32,
	0xd7, 0x04, 0x0a, 0x0b, 0x46, 0x6c, 0x61, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x47, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x1b, 0x2e,
	0x66, 0x6c, 0x61, 0x67, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46,
	0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x66, 0x6c, 0x61,
	0x67, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x1b, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x7a, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3e, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x18, 0x2e, 0x66,
	0x6c, 0x61, 0x67, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x7a, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x44, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x1a,
	0x2e, 0x66, 0x6c, 0x61, 0x67, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6c,
	0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x66, 0x6c, 0x61,
	0x67, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x1b, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x7a, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x53, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x42, 0x6f, 0x6f, 0x6c, 0x65,
	0x61, 0x6e, 0x12, 0x1f, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x73, 0x6f, 0x6c, 0x76, 0x65, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1d, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x7a, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x7a, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x09, 0x57, 0x61, 0x74, 0x63, 0x68, 0x46, 0x6c, 0x61,
	0x67, 0x12, 0x1a, 0x2e, 0x66, 0x6c, 0x61, 0x67, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x66, 0x6c, 0x61, 0x67, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x46, 0x6c,
	0x61, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x30, 0x01, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x74, 0x74, 0x72, 0x69, 0x6c, 0x65,
	0x79, 0x2f, 0x66, 0x6c, 0x61, 0x67, 0x7a, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_v1_flag_service_proto_rawDescOnce sync.Once
	file_api_proto_v1_flag_service_proto_rawDescData = file_api_proto_v1_flag_service_proto_rawDesc
)

func file_api_proto_v1_flag_service_proto_rawDescGZIP() []byte {
	file_api_proto_v1_flag_service_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_flag_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_v1_flag_service_proto_rawDescData)
	})
	return file_api_proto_v1_flag_service_proto_rawDescData
}

var file_api_proto_v1_flag_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_flag_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_v1_flag_service_proto_goTypes = []any{
	(WatchFlagEventType)(0),        // 0: flagz.v1.WatchFlagEventType
	(*Flag)(nil),                   // 1: flagz.v1.Flag
	(*CreateFlagRequest)(nil),      // 2: flagz.v1.CreateFlagRequest
	(*CreateFlagResponse)(nil),     // 3: flagz.v1.CreateFlagResponse
	(*UpdateFlagRequest)(nil),      // 4: flagz.v1.UpdateFlagRequest
	(*UpdateFlagResponse)(nil),     // 5: flagz.v1.UpdateFlagResponse
	(*GetFlagRequest)(nil),         // 6: flagz.v1.GetFlagRequest
	(*GetFlagResponse)(nil),        // 7: flagz.v1.GetFlagResponse
	(*ListFlagsRequest)(nil),       // 8: flagz.v1.ListFlagsRequest
	(*ListFlagsResponse)(nil),      // 9: flagz.v1.ListFlagsResponse
	(*DeleteFlagRequest)(nil),      // 10: flagz.v1.DeleteFlagRequest
	(*DeleteFlagResponse)(nil),     // 11: flagz.v1.DeleteFlagResponse
	(*ResolveBooleanRequest)(nil),  // 12: flagz.v1.ResolveBooleanRequest
	(*ResolveBooleanResponse)(nil), // 13: flagz.v1.ResolveBooleanResponse
	(*ResolveBatchRequest)(nil),    // 14: flagz.v1.ResolveBatchRequest
	(*ResolveBatchResult)(nil),     // 15: flagz.v1.ResolveBatchResult
	(*ResolveBatchResponse)(nil),   // 16: flagz.v1.ResolveBatchResponse
	(*WatchFlagRequest)(nil),       // 17: flagz.v1.WatchFlagRequest
	(*WatchFlagEvent)(nil),         // 18: flagz.v1.WatchFlagEvent
}
var file_api_proto_v1_flag_service_proto_depIdxs = []int32{
	1,  // 0: flagz.v1.CreateFlagRequest.flag:type_name -> flagz.v1.Flag
	1,  // 1: flagz.v1.CreateFlagResponse.flag:type_name -> flagz.v1.Flag
	1,  // 2: flagz.v1.UpdateFlagRequest.flag:type_name -> flagz.v1.Flag
	1,  // 3: flagz.v1.UpdateFlagResponse.flag:type_name -> flagz.v1.Flag
	1,  // 4: flagz.v1.GetFlagResponse.flag:type_name -> flagz.v1.Flag
	1,  // 5: flagz.v1.ListFlagsResponse.flags:type_name -> flagz.v1.Flag
	12, // 6: flagz.v1.ResolveBatchRequest.requests:type_name -> flagz.v1.ResolveBooleanRequest
	15, // 7: flagz.v1.ResolveBatchResponse.results:type_name -> flagz.v1.ResolveBatchResult
	0,  // 8: flagz.v1.WatchFlagEvent.type:type_name -> flagz.v1.WatchFlagEventType
	1,  // 9: flagz.v1.WatchFlagEvent.flag:type_name -> flagz.v1.Flag
	2,  // 10: flagz.v1.FlagService.CreateFlag:input_type -> flagz.v1.CreateFlagRequest
	4,  // 11: flagz.v1.FlagService.UpdateFlag:input_type -> flagz.v1.UpdateFlagRequest
	6,  // 12: flagz.v1.FlagService.GetFlag:input_type -> flagz.v1.GetFlagRequest
	8,  // 13: flagz.v1.FlagService.ListFlags:input_type -> flagz.v1.ListFlagsRequest
	10, // 14: flagz.v1.FlagService.DeleteFlag:input_type -> flagz.v1.DeleteFlagRequest
	12, // 15: flagz.v1.FlagService.ResolveBoolean:input_type -> flagz.v1.ResolveBooleanRequest
	14, // 16: flagz.v1.FlagService.ResolveBatch:input_type -> flagz.v1.ResolveBatchRequest
	17, // 17: flagz.v1.FlagService.WatchFlag:input_type -> flagz.v1.WatchFlagRequest
	3,  // 18: flagz.v1.FlagService.CreateFlag:output_type -> flagz.v1.CreateFlagResponse
	5,  // 19: flagz.v1.FlagService.UpdateFlag:output_type -> flagz.v1.UpdateFlagResponse
	7,  // 20: flagz.v1.FlagService.GetFlag:output_type -> flagz.v1.GetFlagResponse
	9,  // 21: flagz.v1.FlagService.ListFlags:output_type -> flagz.v1.ListFlagsResponse
	11, // 22: flagz.v1.FlagService.DeleteFlag:output_type -> flagz.v1.DeleteFlagResponse
	13, // 23: flagz.v1.FlagService.ResolveBoolean:output_type -> flagz.v1.ResolveBooleanResponse
	16, // 24: flagz.v1.FlagService.ResolveBatch:output_type -> flagz.v1.ResolveBatchResponse
	18, // 25: flagz.v1.FlagService.WatchFlag:output_type -> flagz.v1.WatchFlagEvent
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_proto_v1_flag_service_proto_init() }
func file_api_proto_v1_flag_service_proto_init() {
	if File_api_proto_v1_flag_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_v1_flag_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Flag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_flag_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateFlagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_flag_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateFlagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_flag_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateFlagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_flag_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateFlagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_flag_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetFlagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_flag_service_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetFlagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_flag_service_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ListFlagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_flag_service_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ListFlagsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_flag_service_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteFlagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_flag_service_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteFlagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_flag_service_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ResolveBooleanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_flag_service_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*ResolveBooleanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_flag_service_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*ResolveBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_flag_service_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*ResolveBatchResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_flag_service_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*ResolveBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_flag_service_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*WatchFlagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_flag_service_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*WatchFlagEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_v1_flag_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_flag_service_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_flag_service_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_flag_service_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_flag_service_proto_msgTypes,
	}.Build()
	File_api_proto_v1_flag_service_proto = out.File
	file_api_proto_v1_flag_service_proto_rawDesc = nil
	file_api_proto_v1_flag_service_proto_goTypes = nil
	file_api_proto_v1_flag_service_proto_depIdxs = nil
}
