name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    uses: matt-riley/matt-riley-ci/.github/workflows/go-ci.yml@bcaf4ae43edf7d26421741424b82c842c83e55ce # v2
    with:
      go-version-file: go.mod
      run-race: true
      run-vet: true
      concurrency-suffix: test

  test-go-client:
    uses: matt-riley/matt-riley-ci/.github/workflows/go-ci.yml@bcaf4ae43edf7d26421741424b82c842c83e55ce # v2
    with:
      go-version-file: go.mod
      working-directory: clients/go
      run-vet: true
      concurrency-suffix: test-go-client
