name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    uses: matt-riley/matt-riley-ci/.github/workflows/ci.yml@4ff76b1a606b1fbba163119a65bf7b05f91ab9b6 # v3
    with:
      install: true
      test: true
      concurrency-suffix: test

  test-go-client:
    uses: matt-riley/matt-riley-ci/.github/workflows/ci.yml@4ff76b1a606b1fbba163119a65bf7b05f91ab9b6 # v3
    with:
      install: true
      test: true
      working-directory: clients/go
      concurrency-suffix: test-go-client
